export const routes = {
  FORBIDDEN: 'FORBIDDEN',
  ROUTE_LOGIN: 'LOGIN',
  ROUTE_MAIN: 'MAIN',
  ROUTE_CLASSES: 'CLASSES',
  ROUTE_CLASS: 'CLASS'
}

export const security = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS'
}

export const users = {
  GET_ME_REQUEST: 'GET_ME_REQUEST',
  GET_ME_SUCCESS: 'GET_ME_SUCCESS',
  GET_ME_FAILURE: 'GET_ME_FAILURE'
}

export const classes = {
  GET_CLASSES_REQUEST: 'GET_CLASSES_REQUEST',
  GET_CLASSES_SUCCESS: 'GET_CLASSES_SUCCESS',
  GET_CLASSES_FAILURE: 'GET_CLASSES_FAILURE',
  GET_CLASS_REQUEST: 'GET_CLASS_REQUEST',
  GET_CLASS_SUCCESS: 'GET_CLASS_SUCCESS',
  GET_CLASS_FAILURE: 'GET_CLASS_FAILURE'
}

export const students = {
  GET_STUDENTS_REQUEST: 'GET_STUDENTS_REQUEST',
  GET_STUDENTS_SUCCESS: 'GET_STUDENTS_SUCCESS',
  GET_STUDENTS_FAILURE: 'GET_STUDENTS_FAILURE',
  GET_STUDENT_REQUEST: 'GET_STUDENT_REQUEST',
  GET_STUDENT_SUCCESS: 'GET_STUDENT_SUCCESS',
  GET_STUDENT_FAILURE: 'GET_STUDENT_FAILURE'
}

export const marks = {
  GET_MARKS_REQUEST: 'GET_MARKS_REQUEST',
  GET_MARKS_SUCCESS: 'GET_MARKS_SUCCESS',
  GET_MARKS_FAILURE: 'GET_MARKS_FAILURE',
  GET_MARK_REQUEST: 'GET_MARK_REQUEST',
  GET_MARK_SUCCESS: 'GET_MARK_SUCCESS',
  GET_MARK_FAILURE: 'GET_MARK_FAILURE',
  POST_MARK_REQUEST: 'POST_MARK_REQUEST',
  POST_MARK_SUCCESS: 'POST_MARK_SUCCESS',
  POST_MARK_FAILURE: 'POST_MARK_FAILURE',
  PUT_MARK_REQUEST: 'PUT_MARK_REQUEST',
  PUT_MARK_SUCCESS: 'PUT_MARK_SUCCESS',
  PUT_MARK_FAILURE: 'PUT_MARK_FAILURE'
}

export const teachers = {
  GET_TEACHERS_REQUEST: 'GET_TEACHERS_REQUEST',
  GET_TEACHERS_SUCCESS: 'GET_TEACHERS_SUCCESS',
  GET_TEACHERS_FAILURE: 'GET_TEACHERS_FAILURE',
  GET_TEACHER_REQUEST: 'GET_TEACHER_REQUEST',
  GET_TEACHER_SUCCESS: 'GET_TEACHER_SUCCESS',
  GET_TEACHER_FAILURE: 'GET_TEACHER_FAILURE'
}

export default {
  routes,
  security,
  users,
  classes,
  students,
  marks,
  teachers
}
